---
title: "Tourist Expenditure for the year 2012"
author: "Alan C Bonnici"
date: "Wednesday, December 10, 2014"
output: html_document
---


## Project Data

```{r results='hide',echo=FALSE}
    url = "http://www.opendatamalta.org/ckan/dataset/50cfd96f-246e-4d57-a0ce-86c8ce88e9d6/resource/fad12a26-2965-404f-9320-c0bc82353315/download/Profileofdepartingtourists2012.csv"
    rData = "../data/tourists2012.Rdata"
    load(rData)
```


This document analyses data available for public download from the Open Data Malta website. The dataset being analysed deals with a breakdown of tourist expenditure for the year 2012 by Sex and Age Group.

The data is publically available from `r url`. It was downloaded on **`r downloadDt`**.

The data had to be cleaned up and reprocessed in order to get it into a format that is usable in this app.

## Code Reproducability

The code that downloads the raw data, cleans it up and prepares it for this app forms part of the github repo at https://github.com/chribonn/devdataprod-016/.

This repo contains all the code and data making up this solution. The files and folders are the following:

1  **README.md** - Text file that lists the project question and points to this file.  
2  **/code/code.R** - The code that was used to download and clean up the data.  
3  */data* - The data used in this project.  
4  */shiny* - The code used in the creation of the shiny solution.  

